### ISSUE TITLE
non-zero code: 100 error when installing Node packages

### ISSUE THREAD

**Issue by gidztech** [gidztech/docker-chromium#17]
This is happening for me suddenly in a project I'm using this library on. We haven't changed anything so it's not clear why it's broken now. It works fine on a different laptop.

```
Docker Chromium: Setting Chromium download host to https://storage.googleapis.com...
Docker Chromium: Setting Chromium version to rev-722234...
Docker Chromium: Building Docker image...
Error: Docker Chromium: Failed to build Docker image
Internal Error:
Error: Command failed: docker-compose -f "<<app>>\node_modules\jest-puppeteer-docker\node_modules\docker-chromium\docker\docker-compose.yml" build --build-arg CHROMIUM_ADDITIONAL_ARGS="undefined" --build-arg CHROMIUM_DOWNLOAD_HOST=https://storage.googleapis.com --build-arg CHROMIUM_REVISION=722234 --pull chromium
Building chromium
Service 'chromium' failed to build: The command '/bin/sh -c apt-get update -qqy   && apt-get -qqy install libnss3 libnss3-tools libfontconfig1 wget ca-certificates apt-transport-https inotify-tools unzip   libpangocairo-1.0-0 libx11-xcb-dev libxcomposite-dev libxcursor1 libxdamage1 libxi6 libgconf-2-4 libxtst6 libcups2-dev   libxss-dev libxrandr-dev libasound2-dev libatk1.0-dev libgtk-3-dev ttf-ancient-fonts chromium-codecs-ffmpeg-extra libappindicator3-1   iputils-ping iproute2 curl dumb-init   && rm -rf /var/lib/apt/lists/* /var/cache/apt/* && chmod +x /usr/bin/entrypoint.sh' returned a non-zero code: 100
    at dockerBuild (<<app>>\node_modules\jest-puppeteer-docker\node_modules\docker-chromium\lib\index.js:36:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
```

**Comment by gidztech** [comment]
It is not clear why for some packages I get 400 Bad Request on my work laptop but I was able to solve it by using other mirrors. I decided to add a `useClosestUbuntuMirror` flag to pick the closest mirror, which also can improve performance.
