### ISSUE TITLE
Frequently failing to connect to container in 5 attempts

### ISSUE THREAD

**Issue by TeagueLander** [gidztech/docker-chromium#4]
I'm using the jest-puppeteer-docker plugin to run end-to-end tests and trying to integrate these into my jenkins pipeline.  About 1/5th of the time, when running the tests locally or on jenkins, docker-chromium fails to connect to the container it has launch within 5 attempts.
My error below:
```
Docker Chromium: Successfully started Docker container

Docker Chromium: Contacting Chromium in container...

Docker Chromium: Attempt #2

Docker Chromium: Attempt #3

Docker Chromium: Attempt #4

Docker Chromium: Attempt #5

Docker Chromium: Max number of attempts exceeded. I'm giving up!

(node:13051) UnhandledPromiseRejectionWarning: RequestError: Error: read ECONNRESET

    at new RequestError (/var/lib/jenkins/jobs/penweb-pipe/branches/PR-754/workspace/node_modules/request-promise-core/lib/errors.js:14:15)

    at Request.plumbing.callback (/var/lib/jenkins/jobs/penweb-pipe/branches/PR-754/workspace/node_modules/request-promise-core/lib/plumbing.js:87:29)

    at Request.RP$callback [as _callback] (/var/lib/jenkins/jobs/penweb-pipe/branches/PR-754/workspace/node_modules/request-promise-core/lib/plumbing.js:46:31)

    at self.callback (/var/lib/jenkins/jobs/penweb-pipe/branches/PR-754/workspace/node_modules/request/request.js:185:22)

    at Request.emit (events.js:189:13)

    at Request.onRequestError (/var/lib/jenkins/jobs/penweb-pipe/branches/PR-754/workspace/node_modules/request/request.js:881:8)

    at ClientRequest.emit (events.js:189:13)

    at Socket.socketErrorListener (_http_client.js:392:9)

    at Socket.emit (events.js:189:13)

    at emitErrorNT (internal/streams/destroy.js:82:8)

(node:13051) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:13051) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm hoping the number of attempts can be increased (since they all happen within a second or two anyway) or perhaps be configurable.

**Comment by gidztech** [comment]
I never worked out why it needs several attempts to connect sometimes, but I merged a PR that will allow you to pass in a custom number of attempts and interval between attempts. This should hopefully solve the problem for some, though I've never needed more attempts on my own projects.
